/**
 * Error codes for frontend integration
 * Format: MODULE_ERROR_TYPE_DESCRIPTION
 */
export const ERROR_CODES = {
  // Authentication errors (AUTH_)
  AUTH_USERNAME_EXISTS: 'AUTH_USERNAME_EXISTS',
  AUTH_INVALID_CREDENTIALS: 'AUTH_INVALID_CREDENTIALS',
  AUTH_INVALID_USERNAME_PASSWORD: 'AUTH_INVALID_USERNAME_PASSWORD',
  AUTH_UNAUTHORIZED: 'AUTH_UNAUTHORIZED',

  // Student errors (STUDENT_)
  STUDENT_NOT_FOUND: 'STUDENT_NOT_FOUND',
  STUDENT_GROUP_NOT_FOUND: 'STUDENT_GROUP_NOT_FOUND',
  STUDENT_NEGATIVE_BALANCE_GROUP_CHANGE: 'STUDENT_NEGATIVE_BALANCE_GROUP_CHANGE',
  STUDENT_NOT_DELETED: 'STUDENT_NOT_DELETED',
  STUDENT_MESSAGE_DETERMINATION_FAILED: 'STUDENT_MESSAGE_DETERMINATION_FAILED',
  STUDENT_NO_PARENTS_TO_NOTIFY: 'STUDENT_NO_PARENTS_TO_NOTIFY',

  // Group errors (GROUP_)
  GROUP_NOT_FOUND: 'GROUP_NOT_FOUND',
  GROUP_TEACHER_NOT_FOUND: 'GROUP_TEACHER_NOT_FOUND',
  GROUP_HAS_STUDENTS: 'GROUP_HAS_STUDENTS',

  // Employee errors (EMPLOYEE_)
  EMPLOYEE_NOT_FOUND: 'EMPLOYEE_NOT_FOUND',
  EMPLOYEE_ROLE_NOT_FOUND: 'EMPLOYEE_ROLE_NOT_FOUND',
  EMPLOYEE_INVALID_SALARY_TYPE: 'EMPLOYEE_INVALID_SALARY_TYPE',
  EMPLOYEE_ALREADY_EXISTS: 'EMPLOYEE_ALREADY_EXISTS',

  // Payment errors (PAYMENT_)
  PAYMENT_STUDENT_NOT_FOUND: 'PAYMENT_STUDENT_NOT_FOUND',
  PAYMENT_ADMIN_NOT_FOUND: 'PAYMENT_ADMIN_NOT_FOUND',
  PAYMENT_NEGATIVE_DISCOUNT: 'PAYMENT_NEGATIVE_DISCOUNT',
  PAYMENT_CHEQUE_CLOSED: 'PAYMENT_CHEQUE_CLOSED',

  // Attendance errors (ATTENDANCE_)
  ATTENDANCE_STUDENT_NOT_FOUND: 'ATTENDANCE_STUDENT_NOT_FOUND',
  ATTENDANCE_GROUP_NOT_FOUND: 'ATTENDANCE_GROUP_NOT_FOUND',
  ATTENDANCE_ALREADY_EXISTS: 'ATTENDANCE_ALREADY_EXISTS',
  ATTENDANCE_NOT_FOUND: 'ATTENDANCE_NOT_FOUND',

  // Test errors (TEST_)
  TEST_NOT_FOUND: 'TEST_NOT_FOUND',
  TEST_GROUP_NOT_FOUND: 'TEST_GROUP_NOT_FOUND',
  TEST_ALREADY_EXISTS: 'TEST_ALREADY_EXISTS',

  // Test Result errors (TEST_RESULT_)
  TEST_RESULT_NOT_FOUND: 'TEST_RESULT_NOT_FOUND',
  TEST_RESULT_STUDENT_NOT_FOUND: 'TEST_RESULT_STUDENT_NOT_FOUND',
  TEST_RESULT_TEST_NOT_FOUND: 'TEST_RESULT_TEST_NOT_FOUND',
  TEST_RESULT_ALREADY_EXISTS: 'TEST_RESULT_ALREADY_EXISTS',

  // Parent errors (PARENT_)
  PARENT_NOT_FOUND: 'PARENT_NOT_FOUND',
  PARENT_STUDENT_NOT_FOUND: 'PARENT_STUDENT_NOT_FOUND',
  PARENT_TELEGRAM_ID_EXISTS: 'PARENT_TELEGRAM_ID_EXISTS',

  // Salary errors (SALARY_)
  SALARY_EMPLOYEE_NOT_FOUND: 'SALARY_EMPLOYEE_NOT_FOUND',
  SALARY_INVALID_AMOUNT: 'SALARY_INVALID_AMOUNT',
  SALARY_ALREADY_PAID: 'SALARY_ALREADY_PAID',

  // Config errors (CONFIG_)
  CONFIG_NOT_FOUND: 'CONFIG_NOT_FOUND',
  CONFIG_INVALID_VALUE: 'CONFIG_INVALID_VALUE',

  // Cheque errors (CHEQUE_)
  CHEQUE_ALREADY_CLOSED: 'CHEQUE_ALREADY_CLOSED',
  CHEQUE_NOT_FOUND: 'CHEQUE_NOT_FOUND',

  // Notification errors (NOTIFICATION_)
  NOTIFICATION_SEND_FAILED: 'NOTIFICATION_SEND_FAILED',
  NOTIFICATION_INVALID_RECIPIENT: 'NOTIFICATION_INVALID_RECIPIENT',

  // File errors (FILE_)
  FILE_NOT_FOUND: 'FILE_NOT_FOUND',
  FILE_UPLOAD_FAILED: 'FILE_UPLOAD_FAILED',
  FILE_INVALID_TYPE: 'FILE_INVALID_TYPE',

  // Statistics errors (STATISTICS_)
  STATISTICS_TEACHER_REQUIRED: 'STATISTICS_TEACHER_REQUIRED',
  STATISTICS_TEACHER_NOT_FOUND: 'STATISTICS_TEACHER_NOT_FOUND',
  STATISTICS_INVALID_DATE_FORMAT: 'STATISTICS_INVALID_DATE_FORMAT',
  STATISTICS_INVALID_DATE_RANGE: 'STATISTICS_INVALID_DATE_RANGE',

  // General errors (GENERAL_)
  GENERAL_VALIDATION_FAILED: 'GENERAL_VALIDATION_FAILED',
  GENERAL_INTERNAL_ERROR: 'GENERAL_INTERNAL_ERROR',
  GENERAL_FORBIDDEN: 'GENERAL_FORBIDDEN',
  GENERAL_BAD_REQUEST: 'GENERAL_BAD_REQUEST',
} as const;

export type ErrorCode = typeof ERROR_CODES[keyof typeof ERROR_CODES];
